22 exit built in
ruzafa8/minishell pull request #53
Opened 2023-06-14 18:47 UTC by amorilla42

2023-06-14 21:56 UTC, ruzafa8 commented
@amorilla42 Te he dejado varios comentarios, revísalos y si estás seguro de que está todo bien, mergeas, sino me vas respondiendo aquí

2023-06-14 21:56 UTC, ruzafa8 requested changes

2023-06-14 21:56 UTC, ruzafa8 commented on src/loop_shell.c
> +		ft_printf("exit\n");
Esto se debería de printear en el STDERR?

2023-06-14 21:56 UTC, ruzafa8 commented on src/utils/free.c
> +	close(command->fd_in);
Las variables `fd_in` y `fd_out` storean el file descriptor que se va encontrando en el parser al poner `<`, `>`, `<<` y `>>`. Pero si no hay ningún redir, se le queda un 0. (Sería el stdin, lo cual no tiene sentido). El meaning del 0 es el de NULL.

Eso significa que esa variable puede tener o un fd o un 0. Hay que comprobar que no sea 0, sino estamos closeando stdin!!

`if (command->fd_in)
      close(...)
`

2023-06-14 21:56 UTC, ruzafa8 commented on includes/minishell.h
> +	int			interactive;
¿Esta variable la estás usando en algún lado? ¿Es necesaria?

2023-06-14 21:56 UTC, ruzafa8 commented on includes/minishell.h
> +void			free_envs(t_shell_data *data);
Para que sea más organizado, podemos ponerle a todas las funciones de utils con "utils_" ? Así evitamos problemas de colisión con nombres, y cuando quieras usar algo de utils en vscode solo tienes que escribir utils_ y ya te salen todos los utils.

2023-06-14 21:56 UTC, ruzafa8 commented on src/executer/exec_exit.c
> + * TODO: alomejor CLOSEAR STDIN Y OUT ES TONTERIA???
Yo los closeo para cada proceso del comando. No sé para el proceso principal. Podemos crear una task para revisar

2023-06-16 15:43 UTC, amorilla42 commented on src/loop_shell.c
> +		ft_printf("exit\n");
nope

2023-06-16 15:45 UTC, amorilla42 commented on src/utils/free.c
> +	close(command->fd_in);
hechisimo

2023-06-16 15:47 UTC, amorilla42 commented on src/executer/exec_exit.c
> + * TODO: alomejor CLOSEAR STDIN Y OUT ES TONTERIA???
megustamuchismio

2023-06-16 15:50 UTC, ruzafa8 approved these changes
increible. Menú de medicamento

2023-06-16 15:50 UTC, merged